In [24]:
import pandas as pd
import pickle
import xlrd

In [16]:
%%time

outpatient_charge_df = pd.DataFrame()
chunk_nbr = 1

for chunk in pd.read_csv('../class_data/Provider_Outpatient_Hospital_Charge_Data_by_APC__CY2017.csv', chunksize = 1000):
    if chunk_nbr == 1:
        outpatient_charge_df = outpatient_charge_df.append(chunk)
        chunk_nbr += 1
    else: break
outpatient_charge_df.head()

CPU times: user 15.3 ms, sys: 4.12 ms, total: 19.4 ms
Wall time: 19.3 ms

,Provider_ID,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,Provider_HRR,APC,APC_Desc,Beneficiaries,CAPC_Services,Average_Total_Submitted_Charges,Average_Medicare_Allowed_Amount,Average_Medicare_Payment_Amount,Outlier_Services,Average_Medicare_Outlier_Amount
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249.0,259,9575.01,1038.45,826.28,NaN,NaN
1,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52.0,53,12578.28,1792.60,1423.25,NaN,NaN
2,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26.0,27,11337.61,2113.58,1683.99,0.0,0.0
3,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23.0,23,17116.16,3737.14,2977.55,0.0,0.0
4,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17.0,17,7382.73,1029.46,820.21,0.0,0.0

In [17]:
outpatient_charge_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Provider_ID                      1000 non-null   int64
 1   Provider_Name                    1000 non-null   object
 2   Provider_Street_Address          1000 non-null   object
 3   Provider_City                    1000 non-null   object
 4   Provider_State                   1000 non-null   object
 5   Provider_Zip_Code                1000 non-null   int64
 6   Provider_HRR                     1000 non-null   object
 7   APC                              1000 non-null   int64
 8   APC_Desc                         1000 non-null   object
 9   Beneficiaries                    989 non-null    float64
 10  CAPC_Services                    1000 non-null   int64
 11  Average_Total_Submitted_Charges  1000 non-null   float64
 12  Average_Medicare_Allowed_Amount  1000 non-null   float64
 13  Average_Medicare_Payment_Amount  1000 non-null   float64
 14  Outlier_Services                 788 non-null    float64
 15  Average_Medicare_Outlier_Amount  788 non-null    float64
dtypes: float64(6), int64(4), object(6)
memory usage: 125.1+ KB

In [18]:
outpatient_charge_df.to_pickle("../class_data/outpatient_charge.pkl")

In [19]:
%%time

outpatient_charge_df = pd.read_pickle("../class_data/outpatient_charge.pkl")

CPU times: user 2.02 ms, sys: 1.26 ms, total: 3.27 ms
Wall time: 2.27 ms

In [20]:
outpatient_charge_df.head()

,Provider_ID,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,Provider_HRR,APC,APC_Desc,Beneficiaries,CAPC_Services,Average_Total_Submitted_Charges,Average_Medicare_Allowed_Amount,Average_Medicare_Payment_Amount,Outlier_Services,Average_Medicare_Outlier_Amount
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249.0,259,9575.01,1038.45,826.28,NaN,NaN
1,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52.0,53,12578.28,1792.60,1423.25,NaN,NaN
2,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26.0,27,11337.61,2113.58,1683.99,0.0,0.0
3,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23.0,23,17116.16,3737.14,2977.55,0.0,0.0
4,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17.0,17,7382.73,1029.46,820.21,0.0,0.0

In [28]:
zip_codes = pd.read_excel('../class_data/ZIP_CBSA_032020.xlsx')

In [29]:
zip_codes.head()

   ZIP   CBSA  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
0  501  35620        0.0        1.0        0.0        1.0
1  601  38660        1.0        1.0        1.0        1.0
2  602  10380        1.0        1.0        1.0        1.0
3  603  10380        1.0        1.0        1.0        1.0
4  604  10380        1.0        1.0        1.0        1.0

In [30]:
addendum_df = pd.read_excel('../class_data/2020_january_web_addendum_b.12312019.xlsx')

In [32]:
addendum_df.head()

,Unnamed: 0,Addendum B.-Final OPPS Payment by HCPCS Code for CY 2020,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,CPT codes and descriptions only are copyright ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,HCPCS Code,Short Descriptor,SI,APC,Relative Weight,Payment Rate,National Unadjusted Copayment,Minimum Unadjusted Copayment,Note: Actual copayments would be lower due to ...,* Indicates a Change
2,00100,Anesth salivary gland,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00102,Anesth repair of cleft lip,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00103,Anesth blepharoplasty,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN