In [10]:
import pandas as pd
import pickle

In [32]:
%%time
# option 2

cols = ['National Provider Identifier',
        'Last Name/Organization Name of the Provider',
        'Entity Type of the Provider',
        'City of the Provider',
        'Zip Code of the Provider',
        'State Code of the Provider',
        'Provider Type',
        'Place of Service',
        'Number of Services',
        'Number of Medicare Beneficiaries',
        'Number of Distinct Medicare Beneficiary/Per Day Services',
        'Average Medicare Allowed Amount']

df_payments_2017 = pd.read_csv('../data/Medicare_Provider_Utilization_and_Payment_Data__Physician_and_Other_Supplier_PUF_CY2017.csv', 
                               usecols = cols)
df_payments_2017['year'] = 2017

Wall time: 28.2 s

In [15]:
#load all three csv files and add year column
# need more work on this code
'''%%time
# option 2

cols = ['National Provider Identifier',
        'Last Name/Organization Name of the Provider',
        'Entity Type of the Provider',
        'City of the Provider',
        'Zip Code of the Provider',
        'State Code of the Provider',
        'Provider Type',
        'Place of Service',
        'Number of Services',
        'Number of Medicare Beneficiaries',
        'Number of Distinct Medicare Beneficiary/Per Day Services',
        'Average Medicare Allowed Amount']
years=['CY2017','CY2016','CY2015']

for year in years:
    path ='../data/Medicare_Provider_Utilization_and_Payment_Data__Physician_and_Other_Supplier_PUF_%.csv' % year
    frame = pd.read_csv(path, usecols = cols)

   # frame['year'] = year
    pieces.append(frame)

# Concatenates everything into a single Dataframe
names = pd.concat(pieces, ignore_index=True)'''

TypeError: %c requires int or char

In [46]:
print(df_payments_2017.shape)

(9847443, 13)

In [47]:
df_payments_2017.head()

,national_provider_identifier,last_name_organization_name_of_the_provider,entity_type_of_the_provider,city_of_the_provider,zip_code_of_the_provider,state_code_of_the_provider,provider_type,place_of_service,number_of_services,number_of_medicare_beneficiaries,number_of_distinct_medicare_beneficiary_per_day_services,average_medicare_allowed_amount,year
0,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,100.0,96,100,73.398800,2017
1,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,26.0,25,26,100.080000,2017
2,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,52.0,51,52,136.380000,2017
3,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,59.0,59,59,190.363729,2017
4,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,16.0,16,16,101.680000,2017

In [48]:
#turn columns names to lower case and replace spaces and '/' with '_'
df_payments_2015.columns = map(str.lower, df_payments_2015.columns)
df_payments_2017.columns = df_payments_2017.columns.str.replace(' ', '_')
df_payments_2017.columns = df_payments_2017.columns.str.replace('/', '_')
df_payments_2017.head()

,national_provider_identifier,last_name_organization_name_of_the_provider,entity_type_of_the_provider,city_of_the_provider,zip_code_of_the_provider,state_code_of_the_provider,provider_type,place_of_service,number_of_services,number_of_medicare_beneficiaries,number_of_distinct_medicare_beneficiary_per_day_services,average_medicare_allowed_amount,year
0,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,100.0,96,100,73.398800,2017
1,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,26.0,25,26,100.080000,2017
2,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,52.0,51,52,136.380000,2017
3,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,59.0,59,59,190.363729,2017
4,1003000126,ENKESHAFI,I,CUMBERLAND,215021854,MD,Internal Medicine,F,16.0,16,16,101.680000,2017

In [49]:
#df_payments_2017 = df_payments_2017.drop(labels = 7205022)

In [ ]:
#df_payments_2017[df_payments_2017.national_provider_identifier == 1]

In [36]:
#save it as pkl
df_payments_2017.to_pickle("../data/df_payments_2017.pkl")